import "@mantine/core/styles.css";
import "./globals.css";
import { createTheme, MantineProvider } from "@mantine/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({ children }) {
  return (
    // <MantineProvider theme={theme}>
    <html lang="en">
      <body>{children}</body>
    </html>
    // </MantineProvider>
  );
}
